version: "3"
services:
  mysql:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "asp2023**"
      MYSQL_DATABASE: 'asp-obli-1'
      MYSQL_USERNAME: 'root'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: "asp2023**"
      MYSQL_PORT: '3306'
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    expose:
      - "6379"
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mysql
    environment:
      MY_SQL_DATABASE_NAME: 'asp-obli-1'
      MY_SQL_USERNAME: 'root'
      DB_PASSWORD: "asp2023**"
      MY_SQL_URI: "mysql"
      REDIS_URL: 'redis://redis:6379'
      SENDIN_BLUE_API_KEY: "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"
    command: npm start